#!/usr/bin/env python3
"""
byebytes - find and clean the gigabytes developers forget about.

Two tabs:
  Projects  node_modules, .next, target, .venv, Pods, build ... inside your projects
  Caches    npm/yarn/pnpm, Cypress, Playwright, Xcode, Gradle, Docker, old Node versions ...

  byebytes                     scan your home folder (interactive)
  byebytes ~/code              scan a specific folder
  byebytes --list              plain tables, no UI
  byebytes --json              machine-readable output
  byebytes -m 100M             hide anything smaller than 100 MB

Keys:
  up/down j/k  move          space  select           tab / 1 / 2  switch tab
  PgUp/PgDn    page          a      select all safe  d            delete / clean
  g / G        top / bottom  A      select all       o            reveal in file manager
  s            cycle sort    /      filter           c            copy path
  r            rescan        q/Esc  quit

Safety levels:
  safe       rebuilt automatically (npm install, next build, cargo build ...)
  review     usually fine, but check first (dist/, venvs, Xcode archives ...)
  protected  never deleted (e.g. your active Node version)

Standard library only. Python 3.8+. macOS and Linux (Windows: --list mode).
"""

import argparse
import fnmatch
import json
import locale
import os
import re
import shutil
import stat
import subprocess
import sys
import threading
import time
from concurrent.futures import ThreadPoolExecutor

try:
    import curses
except ImportError:  # Windows without windows-curses -> plain mode only
    curses = None

APP = "byebytes"
__version__ = "1.0.0"

# ════════════════════════════════════════════════════════════════ platform

HOME = os.path.expanduser("~")
IS_MAC = sys.platform == "darwin"
IS_WIN = os.name == "nt"
XDG_CACHE = os.environ.get("XDG_CACHE_HOME") or os.path.join(HOME, ".cache")
XDG_DATA = os.environ.get("XDG_DATA_HOME") or os.path.join(HOME, ".local", "share")
XDG_CONFIG = os.environ.get("XDG_CONFIG_HOME") or os.path.join(HOME, ".config")
OS_CACHE = os.path.join(HOME, "Library", "Caches") if IS_MAC else XDG_CACHE
APP_SUPPORT = os.path.join(HOME, "Library", "Application Support") if IS_MAC else XDG_CONFIG
USE_BLOCKS = not IS_WIN  # count real on-disk usage where available


def H(*parts):
    return os.path.join(HOME, *parts)


def C(*parts):
    return os.path.join(OS_CACHE, *parts)


SAFE, REVIEW, PROTECTED = "safe", "review", "protected"
MEASURING, UNKNOWN = -1, -2

# ════════════════════════════════════════════════════════════════ project rules

PKG = ("package.json",)
GRADLE = ("build.gradle", "build.gradle.kts", "settings.gradle", "settings.gradle.kts", "gradlew")
PYPROJ = ("pyproject.toml", "setup.py", "setup.cfg")
DOTNET = ("*.csproj", "*.fsproj", "*.vbproj")


class Rule:
    __slots__ = ("pattern", "kind", "safety", "markers", "inner", "hint")

    def __init__(self, pattern, kind, safety=SAFE, markers=None, inner=None, hint=""):
        self.pattern = pattern    # folder name (glob allowed)
        self.kind = kind          # short label shown in the KIND column
        self.safety = safety
        self.markers = markers    # a sibling file/folder that must exist (glob allowed)
        self.inner = inner        # a file that must exist inside the folder
        self.hint = hint          # how to get it back


R = Rule
# Order matters when several rules share a folder name: first match wins.
RULES = [
    # JavaScript / TypeScript
    R("node_modules", "node_modules", SAFE, None, None, "npm / yarn / pnpm / bun install"),
    R(".next", "Next.js", SAFE, PKG, None, "rebuilt by next dev / next build"),
    R(".nuxt", "Nuxt", SAFE, PKG, None, "rebuilt by nuxt dev / build"),
    R(".output", "Nuxt/Nitro out", REVIEW, ("nuxt.config.*", "nitro.config.*"), None, "rebuilt by nuxt build"),
    R(".svelte-kit", "SvelteKit", SAFE, PKG, None, "rebuilt by vite dev / build"),
    R(".angular", "Angular cache", SAFE, ("angular.json",), None, "rebuilt by ng serve / build"),
    R(".turbo", "Turborepo", SAFE, PKG, None, "rebuilt by turbo run"),
    R(".nx", "Nx cache", SAFE, ("nx.json",), None, "rebuilt by nx"),
    R(".parcel-cache", "Parcel", SAFE, PKG, None, "rebuilt by parcel"),
    R(".docusaurus", "Docusaurus", SAFE, PKG, None, "rebuilt by docusaurus start / build"),
    R(".astro", "Astro", SAFE, PKG, None, "rebuilt by astro dev / build"),
    R(".expo", "Expo", SAFE, PKG, None, "recreated by expo start"),
    R(".cache", "Gatsby cache", SAFE, ("gatsby-config.*",), None, "rebuilt by gatsby develop / build"),
    R("storybook-static", "Storybook out", REVIEW, PKG, None, "rebuilt by build-storybook"),
    R("coverage", "Test coverage", SAFE, PKG + PYPROJ, None, "regenerated by your test runner"),
    R("bower_components", "Bower", SAFE, ("bower.json",), None, "bower install"),
    # Generic build output: only near a known project file, and gradle/flutter first
    R("build", "Gradle build", SAFE, GRADLE, None, "rebuilt by gradle"),
    R("build", "Flutter build", SAFE, ("pubspec.yaml",), None, "rebuilt by flutter build"),
    R("build", "Build output", REVIEW, PKG + PYPROJ, None, "rebuilt by your build script"),
    R("dist", "Build output", REVIEW, PKG + PYPROJ, None, "rebuilt by your build script"),
    # Rust / JVM
    R("target", "Rust target", SAFE, ("Cargo.toml",), None, "cargo build"),
    R("target", "Maven target", SAFE, ("pom.xml",), None, "mvn package"),
    R("target", "sbt target", SAFE, ("build.sbt",), None, "sbt compile"),
    R(".gradle", "Gradle cache", SAFE, GRADLE, None, "rebuilt by gradle"),
    R(".cxx", "Android NDK", SAFE, GRADLE, None, "rebuilt by gradle"),
    # Python
    R(".venv", "Python venv", REVIEW, None, ("pyvenv.cfg",), "python -m venv .venv, then reinstall deps"),
    R("venv", "Python venv", REVIEW, None, ("pyvenv.cfg",), "python -m venv venv, then reinstall deps"),
    R("env", "Python venv", REVIEW, None, ("pyvenv.cfg",), "python -m venv env, then reinstall deps"),
    R(".tox", "tox", SAFE, None, None, "recreated by tox"),
    R(".nox", "nox", SAFE, None, None, "recreated by nox"),
    R(".pytest_cache", "pytest cache", SAFE, None, None, "recreated by pytest"),
    R(".mypy_cache", "mypy cache", SAFE, None, None, "recreated by mypy"),
    R(".ruff_cache", "ruff cache", SAFE, None, None, "recreated by ruff"),
    # Apple / mobile
    R("Pods", "CocoaPods", SAFE, ("Podfile",), None, "pod install"),
    R(".build", "SwiftPM", SAFE, ("Package.swift",), None, "swift build"),
    R(".dart_tool", "Dart tool", SAFE, ("pubspec.yaml",), None, "dart / flutter pub get"),
    # Other ecosystems
    R("vendor", "Composer", REVIEW, ("composer.json",), None, "composer install"),
    R(".terraform", "Terraform", SAFE, ("*.tf",), None, "terraform init"),
    R(".serverless", "Serverless", SAFE, ("serverless.yml", "serverless.yaml", "serverless.ts"), None, "serverless package"),
    R(".aws-sam", "AWS SAM", SAFE, ("template.yaml", "template.yml", "samconfig.toml"), None, "sam build"),
    R("_build", "Elixir build", SAFE, ("mix.exs",), None, "mix compile"),
    R("deps", "Elixir deps", SAFE, ("mix.exs",), None, "mix deps.get"),
    R(".stack-work", "Haskell stack", SAFE, ("stack.yaml",), None, "stack build"),
    R("dist-newstyle", "Cabal", SAFE, ("*.cabal", "cabal.project"), None, "cabal build"),
    R("elm-stuff", "Elm", SAFE, ("elm.json",), None, "elm make"),
    R(".zig-cache", "Zig cache", SAFE, ("build.zig",), None, "zig build"),
    R("zig-cache", "Zig cache", SAFE, ("build.zig",), None, "zig build"),
    R("cmake-build-*", "CMake build", SAFE, ("CMakeLists.txt",), None, "rebuilt by CMake / CLion"),
    R("obj", ".NET obj", SAFE, DOTNET, None, "dotnet build"),
    R("bin", ".NET bin", REVIEW, DOTNET, None, "dotnet build"),
    # Game engines
    R("Library", "Unity Library", REVIEW, ("ProjectSettings",), None, "Unity re-imports assets (can be slow)"),
    R("Intermediate", "Unreal interm.", SAFE, ("*.uproject",), None, "rebuilt by Unreal"),
    R("DerivedDataCache", "Unreal DDC", SAFE, ("*.uproject",), None, "rebuilt by Unreal"),
    R(".godot", "Godot cache", SAFE, ("project.godot",), None, "re-imported by Godot"),
]
EXACT_RULES = {}
GLOB_RULES = []
for _r in RULES:
    if any(ch in _r.pattern for ch in "*?["):
        GLOB_RULES.append(_r)
    else:
        EXACT_RULES.setdefault(_r.pattern, []).append(_r)

# Files whose mtime tells us when a project was last worked on
PROJECT_FILES = {
    "package.json", "package-lock.json", "yarn.lock", "pnpm-lock.yaml", "bun.lockb", "bun.lock",
    "Cargo.toml", "Cargo.lock", "pyproject.toml", "poetry.lock", "uv.lock", "requirements.txt",
    "Pipfile.lock", "go.mod", "go.sum", "pom.xml", "build.gradle", "build.gradle.kts",
    "Podfile", "Podfile.lock", "pubspec.yaml", "pubspec.lock", "composer.json", "composer.lock",
    "mix.exs", "mix.lock", "Package.swift", "Package.resolved", "CMakeLists.txt", "Gemfile.lock",
}

# Never descended into while scanning projects
SKIP_NAMES = {".git", ".hg", ".svn", ".Trash", ".Trashes", "Library",
              "site-packages", "dist-packages", "__pycache__"}
SKIP_PATHS = {
    # system folders (when scanning from "/")
    "/System", "/Volumes", "/private", "/dev", "/cores", "/Library", "/Applications",
    "/usr", "/bin", "/sbin", "/proc", "/sys", "/snap", "/opt/homebrew", "/nix",
    # tool homes: their contents belong to the Caches tab or are installed software
    H(".nvm"), H(".volta"), H(".fnm"), H(".npm"), H(".bun"), H(".deno"), H(".cache"),
    H(".cargo"), H(".rustup"), H("go", "pkg"), H(".gradle"), H(".m2"), H(".pub-cache"),
    H(".pyenv"), H(".rbenv"), H(".asdf"), H(".sdkman"), H(".nuget"), H(".android"),
    H(".docker"), H(".local", "share"), H(".config"), H("Applications"),
    H("miniconda3"), H("anaconda3"), H("miniforge3"), H("mambaforge"),
    # editor extensions ship their own node_modules - deleting them breaks extensions
    H(".vscode"), H(".vscode-insiders"), H(".vscode-server"), H(".cursor", "extensions"),
    H(".windsurf"), H(".vscode-oss"),
}


def match_rule(name, dirpath, siblings):
    candidates = EXACT_RULES.get(name)
    if candidates is None:
        candidates = [r for r in GLOB_RULES if fnmatch.fnmatchcase(name, r.pattern)]
    for r in candidates:
        if r.inner and not any(os.path.exists(os.path.join(dirpath, name, f)) for f in r.inner):
            continue
        if r.markers and not any(fnmatch.filter(siblings, m) for m in r.markers):
            continue
        return r
    return None


# ════════════════════════════════════════════════════════════════ global caches

class CacheDef:
    def __init__(self, name, group, paths, safety=SAFE, cmd=None, cmd_only=False,
                 note="", sizer=None, needs=None, parse_freed=None):
        self.name = name
        self.group = group
        self.paths = paths            # folders measured & cleared
        self.safety = safety
        self.cmd = cmd                # preferred native cleanup command
        self.cmd_only = cmd_only      # never delete files directly
        self.note = note
        self.sizer = sizer            # custom size function (e.g. Docker)
        self.needs = needs            # path that must exist for the entry to show
        self.parse_freed = parse_freed


def cache_defs():
    cargo = os.environ.get("CARGO_HOME") or H(".cargo")
    gopath = os.environ.get("GOPATH", "").split(os.pathsep)[0] or H("go")
    gomod = os.environ.get("GOMODCACHE") or os.path.join(gopath, "pkg", "mod")
    gradle = os.environ.get("GRADLE_USER_HOME") or H(".gradle")
    pnpm_store = H("Library", "pnpm", "store") if IS_MAC else os.path.join(XDG_DATA, "pnpm", "store")
    xd = H("Library", "Developer")
    D = CacheDef
    defs = [
        # JavaScript
        D("npm cache", "JavaScript", [H(".npm", "_cacache")], cmd=["npm", "cache", "clean", "--force"],
          note="Packages re-download on the next install."),
        D("Yarn cache", "JavaScript", [C("Yarn"), H(".yarn", "berry", "cache")],
          note="Packages re-download on the next install."),
        D("pnpm store", "JavaScript", [pnpm_store], cmd=["pnpm", "store", "prune"],
          note="Runs pnpm store prune: removes only packages no project references."),
        D("Bun cache", "JavaScript", [H(".bun", "install", "cache")],
          note="Packages re-download on the next install."),
        D("Deno cache", "JavaScript", [C("deno")], note="Modules re-download when needed."),
        D("node-gyp headers", "JavaScript", [C("node-gyp")], note="Re-downloaded for native module builds."),
        D("TypeScript cache", "JavaScript", [C("typescript")], note="Editor type cache, rebuilt automatically."),
        D("Electron downloads", "JavaScript", [C("electron"), C("electron-builder")],
          note="Electron binaries re-download when needed."),
        # Test browsers
        D("Cypress binaries", "Test browsers", [C("Cypress")],
          note="Every Cypress version you ever installed. Re-downloads on next install."),
        D("Playwright browsers", "Test browsers", [C("ms-playwright")],
          note="Run `npx playwright install` to get them back."),
        D("Puppeteer browsers", "Test browsers", [H(".cache", "puppeteer")],
          note="Re-downloaded on next puppeteer install."),
        # Python
        D("pip cache", "Python", [C("pip")], note="Wheels re-download on next install."),
        D("uv cache", "Python", [H(".cache", "uv")] + ([C("uv")] if IS_MAC else []),
          cmd=["uv", "cache", "clean"], note="Packages re-download on next install."),
        D("Poetry cache", "Python", [C("pypoetry", "cache"), C("pypoetry", "artifacts")],
          note="Packages re-download on next install."),
        D("Poetry venvs", "Python", [C("pypoetry", "virtualenvs")], safety=REVIEW,
          note="Recreated by `poetry install`, per project."),
        D("Conda packages", "Python", [H(d, "pkgs") for d in ("miniconda3", "anaconda3", "miniforge3", "mambaforge")],
          cmd=["conda", "clean", "--all", "-y"], note="Unused package tarballs and caches."),
        D("Hugging Face", "AI models", [H(".cache", "huggingface")], safety=REVIEW,
          note="Downloaded models & datasets. Big, but re-downloading them can take a while."),
        D("Ollama models", "AI models", [H(".ollama", "models")], safety=REVIEW,
          note="Pulled models. Get them back with `ollama pull`."),
        # Rust / Go / JVM / others
        D("Cargo registry", "Rust", [os.path.join(cargo, "registry", "cache"), os.path.join(cargo, "registry", "src"),
                                     os.path.join(cargo, "git", "checkouts")],
          note="Crates re-download on next build."),
        D("Go module cache", "Go", [gomod], cmd=["go", "clean", "-modcache"], note="Modules re-download on next build."),
        D("Go build cache", "Go", [C("go-build")], cmd=["go", "clean", "-cache"], note="Rebuilt on next build."),
        D("Gradle caches", "JVM", [os.path.join(gradle, "caches"), os.path.join(gradle, "wrapper", "dists")],
          note="Dependencies & Gradle versions re-download on next build."),
        D("Maven repository", "JVM", [H(".m2", "repository")], safety=REVIEW,
          note="Re-downloads, but artifacts you `mvn install`-ed locally will be gone."),
        D("Composer cache", "PHP", [C("composer")], cmd=["composer", "clear-cache"],
          note="Packages re-download on next install."),
        D("NuGet packages", ".NET", [H(".nuget", "packages")], cmd=["dotnet", "nuget", "locals", "all", "--clear"],
          note="Packages re-download on next restore."),
        D("Pub cache", "Dart/Flutter", [H(".pub-cache")], safety=REVIEW,
          note="Also holds globally activated Dart tools. `flutter pub get` restores packages."),
        D("Bazel cache", "Build tools", [H(".cache", "bazel")], safety=REVIEW,
          note="Bazel output bases and repository cache. Rebuilt on next build."),
        D("Android build cache", "Android", [H(".android", "cache"), H(".android", "build-cache")],
          note="Rebuilt automatically."),
        D("Homebrew", "System tools", [C("Homebrew")], cmd=["brew", "cleanup", "--prune=all"],
          note="brew cleanup: removes download cache and old versions of installed formulae."),
        D("Docker", "Docker", [], safety=REVIEW, cmd=["docker", "system", "prune", "-a", "-f"], cmd_only=True,
          sizer=docker_reclaimable, parse_freed=docker_freed,
          note="Removes stopped containers, unused networks, ALL unused images and build cache. Volumes are kept."),
        D("JetBrains caches", "Editors", [C("JetBrains")], safety=REVIEW,
          note="Indexes rebuild on next open (slow first start). Close the IDE first."),
    ]
    for editor in ("Code", "Code - Insiders", "Cursor", "Windsurf", "VSCodium"):
        base = os.path.join(APP_SUPPORT, editor)
        defs.append(D(f"{editor} caches", "Editors",
                      [os.path.join(base, d) for d in ("Cache", "CachedData", "CachedExtensionVSIXs",
                                                       "Code Cache", "GPUCache", "logs")],
                      safety=REVIEW, note="Editor caches & logs. Close the editor first."))
    if IS_MAC:
        defs += [
            D("Xcode DerivedData", "Xcode", [os.path.join(xd, "Xcode", "DerivedData")],
              note="Build products & indexes. Rebuilt on next build."),
            D("Xcode device support", "Xcode",
              [os.path.join(xd, "Xcode", f"{p} DeviceSupport") for p in ("iOS", "watchOS", "tvOS", "visionOS")],
              note="Debug symbols per OS version. Re-created when you connect a device."),
            D("Xcode archives", "Xcode", [os.path.join(xd, "Xcode", "Archives")], safety=REVIEW,
              note="Needed to symbolicate crash reports from builds you shipped."),
            D("Simulator caches", "Xcode", [os.path.join(xd, "CoreSimulator", "Caches")],
              note="Rebuilt automatically."),
            D("Unavailable simulators", "Xcode", [], cmd=["xcrun", "simctl", "delete", "unavailable"],
              cmd_only=True, needs=os.path.join(xd, "CoreSimulator", "Devices"), sizer=lambda: UNKNOWN,
              note="Simulators for runtimes no longer installed."),
            D("CocoaPods cache", "Xcode", [C("CocoaPods")], cmd=["pod", "cache", "clean", "--all"],
              note="Pods re-download on next pod install."),
            D("SwiftPM / Carthage", "Xcode", [C("org.swift.swiftpm"), C("org.carthage.CarthageKit")],
              note="Packages re-download when needed."),
        ]
    return defs


SI_UNITS = {"B": 1, "KB": 1e3, "MB": 1e6, "GB": 1e9, "TB": 1e12, "PB": 1e15}


def _si_bytes(text):
    total = 0.0
    for num, unit in re.findall(r"([\d.]+)\s*([kKMGTP]?B)\b", text):
        total += float(num) * SI_UNITS[unit.upper()]
    return int(total)


def docker_reclaimable():
    try:
        r = subprocess.run(["docker", "system", "df", "--format", "{{.Reclaimable}}"],
                           capture_output=True, text=True, timeout=15)
    except Exception:  # noqa: BLE001
        return UNKNOWN
    if r.returncode != 0:
        return UNKNOWN
    # lines look like "1.2GB (45%)"; drop the percentage before parsing
    return _si_bytes(re.sub(r"\(.*?\)", "", r.stdout))


def docker_freed(output):
    m = re.search(r"Total reclaimed space:\s*(.+)", output)
    return _si_bytes(m.group(1)) if m else 0


# ════════════════════════════════════════════════════════════════ symbols

UNICODE_GLYPHS = {
    "spin": "⠋⠙⠹⠸⠼⠴⠦⠧⠇⠏", "ell": "…", "dot": "·", "cur": "▸", "on": "◉", "off": "○", "lock": "⊘",
    "ok": "✓", "bad": "✗", "logo": " ◆ byebytes ", "caret": "▏", "ge": "≥", "keys": "↑↓",
    "down": "↓", "arrow": "→", "bar": "█", "dash": "—",
}
ASCII_GLYPHS = {
    "spin": "|/-\\", "ell": "...", "dot": "|", "cur": ">", "on": "*", "off": ".", "lock": "-",
    "ok": "+", "bad": "x", "logo": " byebytes ", "caret": "_", "ge": ">=", "keys": "j/k",
    "down": "desc", "arrow": "-", "bar": "#", "dash": "-",
}
G = dict(UNICODE_GLYPHS)

SORTS = (("size", "size {down}"), ("age", "oldest first"), ("name", "name A{arrow}Z"), ("kind", "kind"))
TABS = ("projects", "caches")
TAB_LABELS = {"projects": "Projects", "caches": "Caches"}
STALE_DAYS = 90
BIG = 500 * 1024 ** 2
MEDIUM = 100 * 1024 ** 2


def sort_label(i):
    return SORTS[i][1].format(**G)


def spinner():
    return G["spin"][int(time.time() * 10) % len(G["spin"])]


# ════════════════════════════════════════════════════════════════ helpers

def human(n):
    if n is None or n == MEASURING:
        return G["ell"]
    if n == UNKNOWN:
        return "?"
    for unit in ("B", "KB", "MB", "GB", "TB"):
        if n < 1024 or unit == "TB":
            return f"{n:.0f} {unit}" if unit == "B" else f"{n:.1f} {unit}"
        n /= 1024


def parse_size(text):
    s = text.strip().upper().rstrip("B")
    mult = {"K": 1024, "M": 1024 ** 2, "G": 1024 ** 3, "T": 1024 ** 4}
    if s and s[-1] in mult:
        return int(float(s[:-1]) * mult[s[-1]])
    return int(float(s or 0))


def ago(ts):
    if not ts:
        return G["dash"]
    days = (time.time() - ts) / 86400
    if days < 1:
        return "today"
    if days < 30:
        return f"{int(days)}d ago"
    if days < 365:
        return f"{int(days // 30)}mo ago"
    return f"{days / 365:.1f}y ago"


def is_stale(ts):
    return bool(ts) and time.time() - ts > STALE_DAYS * 86400


def tilde(path):
    if path == HOME or path.startswith(HOME + os.sep):
        return "~" + path[len(HOME):]
    return path


def ltrunc(text, width):
    ell = G["ell"]
    if width <= 0:
        return ""
    if len(text) <= width:
        return text
    if width <= len(ell):
        return text[-width:]
    return ell + text[-(width - len(ell)):]


def bar_len(frac, width):
    n = int(round(max(0.0, min(1.0, frac)) * width))
    return max(1, n) if frac > 0 else 0


def dir_size(path, cancel=None):
    """On-disk bytes under path. Symlinks inside are not followed."""
    total = 0
    stack = [path]
    while stack:
        if cancel is not None and cancel.is_set():
            break
        current = stack.pop()
        try:
            with os.scandir(current) as it:
                for entry in it:
                    try:
                        if entry.is_dir(follow_symlinks=False):
                            stack.append(entry.path)
                        else:
                            st = entry.stat(follow_symlinks=False)
                            total += st.st_blocks * 512 if USE_BLOCKS else st.st_size
                    except OSError:
                        pass
        except OSError:
            pass
    return total


def project_mtime(dirpath, filenames, rule):
    best = 0.0
    for f in filenames:
        if f in PROJECT_FILES or (rule.markers and any(fnmatch.fnmatchcase(f, m) for m in rule.markers)):
            try:
                best = max(best, os.stat(os.path.join(dirpath, f)).st_mtime)
            except OSError:
                pass
    if not best:
        try:
            best = os.stat(dirpath).st_mtime
        except OSError:
            pass
    return best


# ════════════════════════════════════════════════════════════════ deleting

NEVER_DELETE = {os.path.realpath(p) for p in (
    "/", HOME, H("Library"), H("Library", "Caches"), H("Library", "Application Support"),
    H("Library", "Developer"), H(".cache"), H(".config"), H(".local"), XDG_DATA, H("Documents"),
    H("Desktop"), H("Downloads"), H("go"), H(".cargo"), H(".gradle"), H(".npm"), H(".nvm"),
)}


def guard(path):
    real = os.path.realpath(path)
    if real in NEVER_DELETE or len(real.strip(os.sep).split(os.sep)) < 3:
        raise RuntimeError(f"refusing to delete {tilde(path)}")


def _retry_writable(func, path, failed):
    """Make path (and its parent) writable and try again - read-only Go caches etc."""
    try:
        os.chmod(os.path.dirname(path), stat.S_IRWXU)
        if not os.path.islink(path):
            os.chmod(path, stat.S_IRWXU if os.path.isdir(path) else stat.S_IRUSR | stat.S_IWUSR)
        func(path)
    except Exception:  # noqa: BLE001
        failed.append(path)


def remove_tree(path, failed):
    def handler(func, p, _exc):
        _retry_writable(func, p, failed)

    if sys.version_info >= (3, 12):
        shutil.rmtree(path, onexc=handler)
    else:
        shutil.rmtree(path, onerror=handler)


def clear_dir(path, failed):
    """Delete everything inside path, keep the folder itself."""
    try:
        with os.scandir(path) as it:
            children = list(it)
    except OSError as ex:
        failed.append(f"{path} ({ex.strerror})")
        return
    for child in children:
        try:
            if child.is_dir(follow_symlinks=False):
                remove_tree(child.path, failed)
            else:
                os.unlink(child.path)
        except OSError:
            _retry_writable(os.unlink, child.path, failed)


# ════════════════════════════════════════════════════════════════ entries & scanning

class Entry:
    __slots__ = ("key", "tab", "paths", "name", "kind", "safety", "note", "cmd", "action",
                 "mtime", "size", "freed", "status", "selected", "error", "sizer", "parse_freed")

    def __init__(self, tab, paths, name, kind, safety, note, action, cmd=None, mtime=0.0,
                 sizer=None, parse_freed=None):
        self.key = tab + ":" + (paths[0] if paths else name)
        self.tab = tab
        self.paths = paths
        self.name = name
        self.kind = kind
        self.safety = safety
        self.note = note
        self.action = action       # "rmtree" | "clear" | "cmd"
        self.cmd = cmd
        self.mtime = mtime
        self.size = MEASURING
        self.freed = 0
        self.status = ""           # "" | "working" | "done" | "error"
        self.selected = False
        self.error = ""
        self.sizer = sizer
        self.parse_freed = parse_freed

    def measure(self, cancel=None):
        if self.sizer is not None:
            return self.sizer()
        return sum(dir_size(p, cancel) for p in self.paths if os.path.isdir(p))


def node_version_entries():
    active = set()
    try:
        out = subprocess.run(["node", "--version"], capture_output=True, text=True, timeout=5).stdout
        if out.strip():
            active.add(out.strip().lstrip("v"))
    except Exception:  # noqa: BLE001
        pass
    nvm_dir = os.environ.get("NVM_DIR") or H(".nvm")
    default_alias = ""
    try:
        with open(os.path.join(nvm_dir, "alias", "default")) as fh:
            default_alias = fh.read().strip().lstrip("v")
    except OSError:
        pass
    fnm_base = (H("Library", "Application Support", "fnm") if IS_MAC
                else os.path.join(XDG_DATA, "fnm"))
    managers = [
        ("nvm", [os.path.join(nvm_dir, "versions", "node")]),
        ("fnm", [os.path.join(fnm_base, "node-versions"), H(".fnm", "node-versions")]),
        ("volta", [H(".volta", "tools", "image", "node")]),
        ("asdf", [H(".asdf", "installs", "nodejs")]),
        ("mise", [os.path.join(XDG_DATA, "mise", "installs", "node")]),
    ]
    entries = []
    for mgr, bases in managers:
        for base in bases:
            try:
                names = sorted(os.listdir(base))
            except OSError:
                continue
            for name in names:
                path = os.path.join(base, name)
                ver = name.lstrip("v")
                if not ver[:1].isdigit() or os.path.islink(path) or not os.path.isdir(path):
                    continue
                is_default = mgr == "nvm" and default_alias[:1].isdigit() and (
                    ver == default_alias or ver.startswith(default_alias + "."))
                if ver in active or is_default:
                    safety, note = PROTECTED, "Your active / default Node version - kept safe."
                else:
                    safety = REVIEW
                    note = (f"Global npm packages installed under this version go with it. "
                            f"Reinstall with: {mgr} install {ver}")
                entries.append(Entry("caches", [path], f"Node v{ver} ({mgr})", "Node versions",
                                     safety, note, "rmtree"))
    return entries


class Scanner:
    def __init__(self, root, workers=8, projects=True, caches=True):
        self.root = root
        self.workers = workers
        self.want_projects = projects
        self.want_caches = caches
        self.entries = []
        self.lock = threading.Lock()
        self.dirs = 0
        self.walking = projects
        self.done = False
        self.t0 = time.time()
        self.t1 = None
        self.freed = 0
        self.cleaned = 0
        self.active_jobs = 0
        self.cancel = threading.Event()
        self.pool = ThreadPoolExecutor(max_workers=workers)

    def start(self):
        threading.Thread(target=self._run, daemon=True).start()
        return self

    def stop(self):
        self.cancel.set()
        try:
            self.pool.shutdown(wait=False, cancel_futures=True)
        except TypeError:  # Python 3.8
            self.pool.shutdown(wait=False)

    def _add(self, e, futures):
        with self.lock:
            self.entries.append(e)
        futures.append(self.pool.submit(self._measure, e))

    def _measure(self, e):
        e.size = e.measure(self.cancel)

    def _run(self):
        futures = []
        try:
            if self.want_caches:
                self._discover_caches(futures)
            if self.want_projects:
                self._walk(futures)
        finally:
            self.walking = False
            for f in futures:
                try:
                    f.result()
                except Exception:  # noqa: BLE001
                    pass
            self.t1 = time.time()
            self.done = True

    def _discover_caches(self, futures):
        for d in cache_defs():
            if d.cmd_only or d.sizer:
                if not (d.cmd and shutil.which(d.cmd[0])):
                    continue
                if d.needs and not os.path.isdir(d.needs):
                    continue
                paths = []
            else:
                paths = [p for p in d.paths if os.path.isdir(p) and not os.path.islink(p)]
                if not paths:
                    continue
            use_cmd = bool(d.cmd and shutil.which(d.cmd[0]))
            e = Entry("caches", paths, d.name, d.group, d.safety, d.note,
                      "cmd" if use_cmd else "clear", cmd=d.cmd if use_cmd else None,
                      sizer=d.sizer, parse_freed=d.parse_freed)
            self._add(e, futures)
        for e in node_version_entries():
            self._add(e, futures)

    def _walk(self, futures):
        for dirpath, dirnames, filenames in os.walk(self.root, followlinks=False):
            if self.cancel.is_set():
                break
            self.dirs += 1
            siblings = filenames + dirnames
            keep = []
            for d in dirnames:
                full = os.path.join(dirpath, d)
                if full in SKIP_PATHS:
                    continue
                rule = match_rule(d, dirpath, siblings)
                if rule is not None:
                    if not os.path.islink(full):
                        rel = os.path.relpath(full, self.root)
                        e = Entry("projects", [full], rel, rule.kind, rule.safety, rule.hint,
                                  "rmtree", mtime=project_mtime(dirpath, filenames, rule))
                        self._add(e, futures)
                    continue  # never descend into a matched folder
                if d in SKIP_NAMES:
                    continue
                keep.append(d)
            dirnames[:] = keep

    # ── cleaning ──────────────────────────────────────────────
    def clean(self, targets):
        for e in targets:
            e.status = "working"
            e.selected = False
            e.error = ""
        with self.lock:
            self.active_jobs += 1

        def work():
            try:
                for e in targets:
                    self._clean_one(e)
            finally:
                with self.lock:
                    self.active_jobs -= 1

        threading.Thread(target=work, daemon=True).start()

    def _clean_one(self, e):
        before = e.size
        failed = []
        output = ""
        try:
            if e.action == "cmd":
                env = dict(os.environ, HOMEBREW_NO_AUTO_UPDATE="1")
                r = subprocess.run(e.cmd, cwd=HOME, stdin=subprocess.DEVNULL, capture_output=True,
                                   text=True, timeout=3600, env=env)
                output = r.stdout + r.stderr
                if r.returncode != 0:
                    lines = [ln for ln in output.strip().splitlines() if ln.strip()]
                    raise RuntimeError(f"`{' '.join(e.cmd)}` failed: {lines[-1] if lines else r.returncode}")
            else:
                for p in e.paths:
                    guard(p)
                    if e.action == "rmtree":
                        remove_tree(p, failed)
                    else:
                        clear_dir(p, failed)
        except Exception as ex:  # noqa: BLE001
            e.error = str(ex)

        if e.sizer is not None:
            after = e.sizer()
        else:
            after = sum(dir_size(p) for p in e.paths if os.path.isdir(p))
        if e.parse_freed and output:
            freed = e.parse_freed(output)
        elif before >= 0 and after >= 0:
            freed = max(0, before - after)
        else:
            freed = 0
        if e.action != "rmtree" or e.error or failed:
            e.size = after
        with self.lock:
            self.freed += freed
        e.freed = freed
        if failed and not e.error:
            e.error = f"{len(failed)} item(s) couldn't be removed, e.g. {tilde(failed[0])}"
        if e.error:
            e.status = "error"
        else:
            e.status = "done"
            with self.lock:
                self.cleaned += 1


# ════════════════════════════════════════════════════════════════ interactive UI

COL_SIZE, COL_BAR, COL_C3, COL_KIND, COL_NAME = 4, 14, 26, 37, 54
BAR_W, KIND_W = 10, 15


class TabState:
    def __init__(self):
        self.cursor = 0
        self.top = 0
        self.cur_key = None
        self.user_moved = False


class App:
    def __init__(self, scr, scanner, min_size):
        self.scr = scr
        self.sc = scanner
        self.min_size = min_size
        self.tab = "projects" if scanner.want_projects else "caches"
        self.ts = {t: TabState() for t in TABS}
        self.rows = []
        self.all_items = []
        self.sort_i = 0
        self.filter = ""
        self.filtering = False
        self.msg = None
        self.c = {}

    @property
    def st(self):
        return self.ts[self.tab]

    # ── setup ──────────────────────────────────────────────────
    def init_colors(self):
        names = ("accent", "red", "yellow", "green", "magenta", "title",
                 "bar_red", "bar_yellow", "bar_green")
        self.c = {n: 0 for n in names}
        if not curses.has_colors():
            self.c["title"] = curses.A_REVERSE
            return
        curses.start_color()
        bg = -1
        try:
            curses.use_default_colors()
        except curses.error:
            bg = curses.COLOR_BLACK
        spec = [
            ("accent", curses.COLOR_CYAN, bg), ("red", curses.COLOR_RED, bg),
            ("yellow", curses.COLOR_YELLOW, bg), ("green", curses.COLOR_GREEN, bg),
            ("magenta", curses.COLOR_MAGENTA, bg), ("title", curses.COLOR_BLACK, curses.COLOR_CYAN),
            ("bar_red", curses.COLOR_BLACK, curses.COLOR_RED),
            ("bar_yellow", curses.COLOR_BLACK, curses.COLOR_YELLOW),
            ("bar_green", curses.COLOR_BLACK, curses.COLOR_GREEN),
        ]
        for i, (name, fg, b) in enumerate(spec, 1):
            curses.init_pair(i, fg, b)
            self.c[name] = curses.color_pair(i)
        self.c["title"] |= curses.A_BOLD

    def size_attr(self, size):
        if size >= BIG:
            return self.c["red"] | curses.A_BOLD
        if size >= MEDIUM:
            return self.c["yellow"]
        return self.c["green"]

    def bar_attr(self, size):
        key = "bar_red" if size >= BIG else "bar_yellow" if size >= MEDIUM else "bar_green"
        return self.c[key] or curses.A_REVERSE

    # ── data ───────────────────────────────────────────────────
    def visible(self):
        with self.sc.lock:
            items = list(self.sc.entries)
        self.all_items = items
        f = self.filter.lower()
        rows = [
            e for e in items
            if e.tab == self.tab
            and not (0 <= e.size < self.min_size and e.status != "done")
            and (not f or f in e.name.lower() or f in e.kind.lower())
        ]
        mode = SORTS[self.sort_i][0]
        if mode == "size":
            rows.sort(key=lambda e: (e.size == MEASURING, e.size == UNKNOWN, -e.size))
        elif mode == "age":
            rows.sort(key=lambda e: e.mtime or float("inf"))
        elif mode == "name":
            rows.sort(key=lambda e: e.name.lower())
        else:
            rows.sort(key=lambda e: (e.kind.lower(), -e.size))
        return rows

    def sync_cursor(self):
        st, n = self.st, len(self.rows)
        if not n:
            st.cursor = 0
            return
        if not st.user_moved:
            st.cursor = 0
        elif st.cur_key is not None:
            for i, e in enumerate(self.rows):
                if e.key == st.cur_key:
                    st.cursor = i
                    break
        st.cursor = max(0, min(st.cursor, n - 1))
        st.cur_key = self.rows[st.cursor].key

    def current(self):
        return self.rows[self.st.cursor] if self.rows else None

    def move(self, delta):
        if not self.rows:
            return
        st = self.st
        st.user_moved = True
        st.cursor = max(0, min(st.cursor + delta, len(self.rows) - 1))
        st.cur_key = self.rows[st.cursor].key

    def flash(self, text, attr=None, secs=4):
        self.msg = (text, self.c["accent"] if attr is None else attr, time.time() + secs)

    # ── drawing ────────────────────────────────────────────────
    def put(self, y, x, text, attr=0):
        h, w = self.scr.getmaxyx()
        if not (0 <= y < h) or x >= w:
            return x + len(text)
        t = text[: max(0, w - x)]
        try:
            self.scr.addstr(y, x, t, attr)
        except curses.error:
            pass  # writing the bottom-right cell raises; harmless
        return x + len(t)

    def list_height(self):
        return self.scr.getmaxyx()[0] - 5

    def draw(self):
        self.scr.erase()
        h, w = self.scr.getmaxyx()
        if h < 9 or w < 72:
            self.put(0, 0, "Terminal too small - make it at least 72x9")
            self.scr.refresh()
            return
        self.draw_header(w)
        self.draw_list(h, w)
        self.draw_footer(h, w)
        self.scr.refresh()

    def draw_header(self, w):
        sc, items, C = self.sc, self.all_items, self.c
        spin, dot = spinner(), G["dot"]
        dim, bold = curses.A_DIM, curses.A_BOLD

        # line 0: logo, root, status
        measuring = sum(1 for e in items if e.size == MEASURING)
        if sc.walking:
            n_proj = sum(1 for e in items if e.tab == "projects")
            status, sattr = f"{spin} scanning {dot} {sc.dirs:,} dirs {dot} {n_proj} found", C["accent"]
        elif not sc.done:
            status, sattr = f"{spin} measuring {dot} {measuring} left", C["accent"]
        else:
            status, sattr = f"{G['ok']} done in {sc.t1 - sc.t0:.1f}s {dot} {sc.dirs:,} dirs", C["green"]
        if sc.active_jobs:
            status, sattr = f"{spin} cleaning {dot} " + status[2:], C["yellow"]
        x = self.put(0, 0, G["logo"], C["title"])
        room = w - x - len(status) - 4
        if sc.want_projects:
            self.put(0, x + 1, ltrunc(tilde(sc.root), room), bold)
        self.put(0, max(0, w - len(status) - 1), status, sattr)

        # line 1: tabs + selection/freed
        x = 0
        for i, t in enumerate(TABS):
            if t == "projects" and not sc.want_projects or t == "caches" and not sc.want_caches:
                continue
            tab_items = [e for e in items if e.tab == t and e.status != "done"]
            total = sum(max(0, e.size) for e in tab_items)
            label = f" {i + 1} {TAB_LABELS[t]} {human(total)} "
            x = self.put(1, x, label, C["title"] if t == self.tab else dim) + 1
        sel = [e for e in self.rows if e.selected]
        segs = [("Selected ", dim), (human(sum(max(0, e.size) for e in sel)), bold | C["magenta"]),
                (f" ({len(sel)})", dim), ("   Freed ", dim), (human(sc.freed), bold | C["green"])]
        right_len = sum(len(t) for t, _ in segs)
        if x + right_len + 2 < w:
            rx = w - right_len - 1
            for text, attr in segs:
                rx = self.put(1, rx, text, attr)

        # line 2: column headers + sort / filter / position
        c3 = "TOUCHED" if self.tab == "projects" else "CLEANS BY"
        name = "FOLDER" if self.tab == "projects" else "CACHE"
        hdr = (" " * COL_SIZE + "SIZE".rjust(9) + " " + "USAGE".ljust(BAR_W) + "  " + c3.rjust(9)
               + "  " + "KIND".ljust(KIND_W) + "  " + name)
        self.put(2, 0, hdr, dim | bold)
        right = f"sort: {sort_label(self.sort_i)}"
        if self.filter:
            right = f"filter: {self.filter}  " + right
        if self.min_size:
            right = f"{G['ge']} {human(self.min_size)}  " + right
        if self.rows:
            right += f"  {self.st.cursor + 1}/{len(self.rows)}"
        if len(hdr) + len(right) + 3 < w:
            self.put(2, w - len(right) - 1, right, dim)

    def draw_list(self, h, w):
        top_y, lh, rows, st = 3, h - 5, self.rows, self.st
        if not rows:
            if self.filter:
                text = "Nothing matches the filter."
            elif not self.sc.done:
                text = "Looking around" + G["ell"]
            elif self.tab == "projects":
                text = "No project folders found. Clean as a whistle."
            else:
                text = "No known caches found on this machine."
            self.put(top_y + lh // 2, max(0, (w - len(text)) // 2), text, curses.A_DIM)
            return
        if st.cursor < st.top:
            st.top = st.cursor
        if st.cursor >= st.top + lh:
            st.top = st.cursor - lh + 1
        st.top = max(0, min(st.top, max(0, len(rows) - lh)))
        biggest = max((e.size for e in rows if e.size > 0 and e.status != "done"), default=1)
        for i in range(lh):
            idx = st.top + i
            if idx >= len(rows):
                break
            self.draw_row(top_y + i, w, rows[idx], idx == st.cursor, biggest)

    def draw_row(self, y, w, e, is_cur, biggest):
        C, spin = self.c, spinner()
        rev = curses.A_REVERSE | curses.A_BOLD
        dim = curses.A_DIM
        if is_cur:
            self.put(y, 0, " " * (w - 1), rev)

        def a(attr):
            return rev if is_cur else attr

        done = e.status == "done"
        self.put(y, 0, G["cur"] if is_cur else " ", a(C["accent"]))
        if e.safety == PROTECTED:
            mark, mattr = G["lock"], C["red"]
        elif e.selected:
            mark, mattr = G["on"], C["magenta"] | curses.A_BOLD
        else:
            mark, mattr = G["off"], dim
        self.put(y, 2, mark, a(mattr))

        # size
        if done:
            shown = human(e.freed) if e.freed or e.size >= 0 else "?"
            self.put(y, COL_SIZE, shown.rjust(9), a(C["green"]))
        else:
            sattr = dim if e.size < 0 else self.size_attr(e.size)
            self.put(y, COL_SIZE, human(e.size).rjust(9), a(sattr))

        # usage bar / status
        txt = None
        if e.status == "working":
            verb = {"rmtree": "deleting", "clear": "clearing", "cmd": "running"}[e.action]
            txt, at = f"{spin} {verb}", C["yellow"]
        elif done:
            txt, at = f"{G['ok']} freed", C["green"]
        elif e.status == "error":
            txt, at = f"{G['bad']} failed", C["red"]
        elif e.size == MEASURING:
            txt, at = f"{spin} measure", dim
        if txt is not None:
            self.put(y, COL_BAR, txt.ljust(BAR_W)[:BAR_W], a(at))
        elif e.size > 0:
            n = bar_len(e.size / biggest, BAR_W)
            if curses.has_colors():
                self.put(y, COL_BAR, " " * n, self.bar_attr(e.size))
            else:
                self.put(y, COL_BAR, G["bar"] * n, a(0))

        # third column: touched (projects) / method (caches)
        if e.tab == "projects":
            c3 = ago(e.mtime)
            c3attr = C["yellow"] if is_stale(e.mtime) and not done else dim
        else:
            c3 = {"cmd": "command", "clear": "delete", "rmtree": "delete"}[e.action]
            c3attr = C["accent"] if e.action == "cmd" else dim
        self.put(y, COL_C3, c3.rjust(9), a(c3attr))

        # kind
        kattr = C["yellow"] if e.safety == REVIEW else (C["red"] if e.safety == PROTECTED else dim)
        self.put(y, COL_KIND, e.kind[:KIND_W], a(kattr))

        # name
        self.put(y, COL_NAME, ltrunc(e.name, w - COL_NAME - 1), a(dim if done else 0))

    def detail_line(self, e):
        """(text, attr) describing the item under the cursor."""
        C = self.c
        if e.error:
            return f"{G['bad']} {e.error}", C["red"]
        if e.action == "cmd":
            where = "runs: " + " ".join(e.cmd)
        elif len(e.paths) > 1:
            where = f"{tilde(e.paths[0])} +{len(e.paths) - 1} more"
        else:
            where = tilde(e.paths[0]) if e.paths else ""
        label = {SAFE: "", REVIEW: "review: ", PROTECTED: "protected: "}[e.safety]
        how = ("restore: " + e.note) if e.tab == "projects" else e.note
        attr = {SAFE: curses.A_DIM, REVIEW: C["yellow"], PROTECTED: C["red"]}[e.safety]
        return f"{where}  {G['dot']}  {label}{how}", attr

    def draw_footer(self, h, w):
        C = self.c
        if self.msg and self.msg[2] > time.time():
            self.put(h - 2, 1, self.msg[0][: w - 2], self.msg[1])
        else:
            e = self.current()
            if e is not None:
                text, attr = self.detail_line(e)
                self.put(h - 2, 1, text[: w - 2], attr)

        y = h - 1
        if self.filtering:
            x = self.put(y, 0, " / ", C["title"])
            x = self.put(y, x + 1, self.filter + G["caret"], curses.A_BOLD)
            self.put(y, x + 2, f"enter keep {G['dot']} esc clear", curses.A_DIM)
            return
        keys = [("tab", "switch"), (G["keys"], "move"), ("space", "select"), ("a/A", "all"),
                ("d", "clean"), ("o", "reveal"), ("c", "copy"), ("s", "sort"), ("/", "filter"),
                ("r", "rescan"), ("q", "quit")]
        x = 1
        for key, label in keys:
            if x + len(key) + len(label) + 3 >= w:
                break
            x = self.put(y, x, key, C["accent"] | curses.A_BOLD)
            x = self.put(y, x + 1, label, curses.A_DIM) + 2

    def confirm(self, text):
        self.draw()
        h, w = self.scr.getmaxyx()
        attr = self.c["red"] | curses.A_REVERSE | curses.A_BOLD
        self.put(h - 1, 0, " " * (w - 1), attr)
        self.put(h - 1, 1, text[: w - 2], attr)
        self.scr.refresh()
        self.scr.timeout(-1)
        try:
            key = self.scr.get_wch()
        except curses.error:
            key = ""
        finally:
            self.scr.timeout(100)
        return key in ("y", "Y")

    # ── actions ────────────────────────────────────────────────
    def selectable(self, e):
        return e.status in ("", "error") and e.safety != PROTECTED

    def clean(self):
        targets = [e for e in self.rows if e.selected and self.selectable(e)]
        if not targets:
            e = self.current()
            if e is None or e.status in ("working", "done"):
                return
            if e.safety == PROTECTED:
                self.flash(f"{e.name} is protected: {e.note}", self.c["red"])
                return
            targets = [e]
        if any(e.size == MEASURING for e in targets):
            self.flash("Still measuring - give it a moment.", self.c["yellow"])
            return
        total = sum(max(0, e.size) for e in targets)
        n_review = sum(1 for e in targets if e.safety == REVIEW)
        if len(targets) == 1:
            e = targets[0]
            if e.action == "cmd":
                q = f"Run `{' '.join(e.cmd)}` ({human(total)})?"
            elif e.action == "clear":
                q = f"Clear {e.name} ({human(total)})?"
            else:
                q = f"Permanently delete {e.name} ({human(total)})?"
            if e.safety == REVIEW:
                q = "[review] " + q
        else:
            q = f"Clean {len(targets)} items ({human(total)})"
            q += f" - {n_review} marked review!" if n_review else "?"
        if self.confirm(q + "  y / N"):
            self.sc.clean(targets)
            self.flash(f"Cleaning {human(total)}{G['ell']}", self.c["yellow"])
        else:
            self.flash("Cancelled.", curses.A_DIM)

    def select_all(self, include_review):
        allowed = (SAFE, REVIEW) if include_review else (SAFE,)
        cand = [e for e in self.rows if self.selectable(e) and e.safety in allowed]
        if not cand:
            return
        value = not all(e.selected for e in cand)
        for e in cand:
            e.selected = value
        what = "all safe + review" if include_review else "all safe"
        self.flash(f"{'Selected' if value else 'Unselected'} {what} items ({len(cand)})")

    def target_path(self, e):
        if e.paths:
            return e.paths[0]
        return None

    def reveal(self):
        e = self.current()
        p = self.target_path(e) if e else None
        if not p:
            return
        target = p if os.path.exists(p) else os.path.dirname(p)
        try:
            if IS_MAC:
                cmd = ["open", "-R", target]
            elif shutil.which("xdg-open"):
                cmd = ["xdg-open", os.path.dirname(target)]
            else:
                self.flash("No file manager opener found.", self.c["yellow"])
                return
            subprocess.Popen(cmd, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
            self.flash(f"Opened {tilde(target)}")
        except Exception as ex:  # noqa: BLE001
            self.flash(f"Couldn't open: {ex}", self.c["red"])

    def copy(self):
        e = self.current()
        if e is None:
            return
        text = self.target_path(e) or " ".join(e.cmd or [])
        for cmd in (["pbcopy"], ["wl-copy"], ["xclip", "-selection", "clipboard"]):
            if shutil.which(cmd[0]):
                subprocess.run(cmd, input=text.encode(), check=False)
                self.flash(f"Copied {tilde(text)}")
                return
        self.flash("No clipboard tool found (pbcopy / wl-copy / xclip).", self.c["yellow"])

    def rescan(self):
        if self.sc.active_jobs:
            self.flash("Wait for cleaning to finish first.", self.c["yellow"])
            return
        old = self.sc
        old.stop()
        self.sc = Scanner(old.root, old.workers, old.want_projects, old.want_caches)
        self.sc.freed, self.sc.cleaned = old.freed, old.cleaned
        self.sc.start()
        self.ts = {t: TabState() for t in TABS}
        self.flash("Rescanning" + G["ell"])

    def switch_tab(self, tab=None):
        avail = [t for t in TABS if (t == "projects" and self.sc.want_projects)
                 or (t == "caches" and self.sc.want_caches)]
        if tab is None:
            tab = avail[(avail.index(self.tab) + 1) % len(avail)]
        if tab in avail:
            self.tab = tab

    # ── input ──────────────────────────────────────────────────
    def on_filter_key(self, k):
        if k in ("\n", "\r", curses.KEY_ENTER):
            self.filtering = False
        elif k == "\x1b":
            self.filter, self.filtering = "", False
        elif k in (curses.KEY_BACKSPACE, "\x7f", "\b"):
            self.filter = self.filter[:-1]
        elif isinstance(k, str) and k.isprintable():
            self.filter += k
        self.st.user_moved = False

    def on_key(self, k):
        lh = self.list_height()
        if k == "\x1b" and self.filter:
            self.filter = ""
        elif k in ("q", "Q", "\x1b"):
            if self.sc.active_jobs and not self.confirm(
                    "Cleaning still running - quit anyway and leave it half done?  y / N"):
                return True
            return False
        elif k in ("\t", curses.KEY_BTAB, curses.KEY_RIGHT, curses.KEY_LEFT):
            self.switch_tab()
        elif k in ("1", "2"):
            self.switch_tab(TABS[int(k) - 1])
        elif k in (curses.KEY_UP, "k"):
            self.move(-1)
        elif k in (curses.KEY_DOWN, "j"):
            self.move(1)
        elif k == curses.KEY_PPAGE:
            self.move(-lh)
        elif k == curses.KEY_NPAGE:
            self.move(lh)
        elif k in (curses.KEY_HOME, "g"):
            self.move(-len(self.rows))
        elif k in (curses.KEY_END, "G"):
            self.move(len(self.rows))
        elif k == " ":
            e = self.current()
            if e is not None and e.safety == PROTECTED:
                self.flash(f"{e.name} is protected: {e.note}", self.c["red"])
            elif e is not None and self.selectable(e):
                e.selected = not e.selected
                self.move(1)
        elif k == "a":
            self.select_all(False)
        elif k == "A":
            self.select_all(True)
        elif k in ("d", "D", "x", curses.KEY_DC):
            self.clean()
        elif k == "o":
            self.reveal()
        elif k == "c":
            self.copy()
        elif k == "s":
            self.sort_i = (self.sort_i + 1) % len(SORTS)
            self.flash(f"Sorted by {sort_label(self.sort_i)}")
        elif k == "/":
            self.filtering = True
        elif k == "r":
            self.rescan()
        return True

    def run(self):
        try:
            curses.curs_set(0)
        except curses.error:
            pass
        self.init_colors()
        self.scr.keypad(True)
        self.scr.timeout(100)
        while True:
            self.rows = self.visible()
            self.sync_cursor()
            self.draw()
            try:
                k = self.scr.get_wch()
            except curses.error:
                continue  # timeout -> redraw (spinner, live results)
            if k == curses.KEY_RESIZE:
                continue
            if self.filtering:
                self.on_filter_key(k)
            elif not self.on_key(k):
                return


# ════════════════════════════════════════════════════════════════ plain mode

def run_plain(sc, min_size, as_json):
    tty = sys.stderr.isatty()
    try:
        while not sc.done:
            if tty:
                sys.stderr.write(f"\r\033[K{spinner()} scanning {G['dot']} {sc.dirs:,} dirs "
                                 f"{G['dot']} {len(sc.entries)} found")
                sys.stderr.flush()
            time.sleep(0.1)
    except KeyboardInterrupt:
        sc.stop()
        if tty:
            sys.stderr.write("\r\033[K")
        print("Interrupted.", file=sys.stderr)
        return 130
    if tty:
        sys.stderr.write("\r\033[K")
        sys.stderr.flush()

    def keep(e):
        return not (0 <= e.size < min_size)

    def by_size(e):
        return -e.size if e.size >= 0 else 1

    projects = sorted((e for e in sc.entries if e.tab == "projects" and keep(e)), key=by_size)
    caches = sorted((e for e in sc.entries if e.tab == "caches" and keep(e)), key=by_size)

    if as_json:
        out = {
            "projects": [{
                "path": e.paths[0], "kind": e.kind, "safety": e.safety, "bytes": e.size,
                "size": human(e.size), "restore": e.note,
                "last_touched": time.strftime("%Y-%m-%dT%H:%M:%S", time.localtime(e.mtime)) if e.mtime else None,
            } for e in projects] if sc.want_projects else None,
            "caches": [{
                "name": e.name, "group": e.kind, "safety": e.safety,
                "bytes": e.size if e.size >= 0 else None, "size": human(e.size),
                "paths": e.paths, "command": e.cmd, "note": e.note,
            } for e in caches] if sc.want_caches else None,
        }
        json.dump(out, sys.stdout, indent=2)
        print()
        return 0

    color = sys.stdout.isatty()

    def paint(text, code):
        return f"\033[{code}m{text}\033[0m" if color else text

    def size_code(n):
        return "1;31" if n >= BIG else "33" if n >= MEDIUM else "32"

    def safety_mark(e):
        return {SAFE: " ", REVIEW: paint("?", "33"), PROTECTED: paint("#", "31")}[e.safety]

    if sc.want_projects:
        print(paint(f"PROJECTS  {tilde(sc.root)}", "1;36"))
        if projects:
            print(paint(f"  {'SIZE':>9}  {'TOUCHED':>9}  {'KIND':<15}  FOLDER", "2"))
            for e in projects:
                print(f"{safety_mark(e)} {paint(human(e.size).rjust(9), size_code(e.size))}  "
                      f"{paint(ago(e.mtime).rjust(9), '33' if is_stale(e.mtime) else '2')}  "
                      f"{e.kind:<15}  {tilde(e.paths[0])}")
            total = sum(max(0, e.size) for e in projects)
            print(f"  {len(projects)} folders {G['dot']} {paint(human(total), '1')}")
        else:
            print("  nothing found")
        print()
    if sc.want_caches:
        print(paint("CACHES", "1;36"))
        if caches:
            print(paint(f"  {'SIZE':>9}  {'GROUP':<15}  {'CACHE':<24}  LOCATION / COMMAND", "2"))
            for e in caches:
                where = " ".join(e.cmd) if e.cmd else tilde(e.paths[0]) + (
                    f" +{len(e.paths) - 1}" if len(e.paths) > 1 else "")
                print(f"{safety_mark(e)} {paint(human(e.size).rjust(9), size_code(max(0, e.size)))}  "
                      f"{e.kind:<15}  {e.name:<24}  {paint(where, '2')}")
            total = sum(max(0, e.size) for e in caches)
            print(f"  {len(caches)} caches {G['dot']} {paint(human(total), '1')}")
        else:
            print("  nothing found")
        print()
    print(paint(f"? = review before deleting   # = protected   "
                f"scanned {sc.dirs:,} dirs in {sc.t1 - sc.t0:.1f}s", "2"))
    return 0


# ════════════════════════════════════════════════════════════════ main

def utf8_locale():
    enc = (locale.getpreferredencoding(False) or "").upper().replace("UTF8", "UTF-8")
    return "UTF-8" in enc


def unicode_safe():
    """Can this curses build draw multi-byte characters reliably?"""
    if not utf8_locale():
        return False
    version = getattr(curses, "ncurses_version", None) if curses else None
    # macOS system Python ships ncurses 5.4 (2004), which garbles wide chars on partial redraws
    return version is None or tuple(version)[:1] >= (6,)


def _main():
    ap = argparse.ArgumentParser(
        prog=APP,
        description="Find and clean project build folders (node_modules, target, .venv ...) "
                    "and global developer caches.")
    ap.add_argument("path", nargs="?", default="~",
                    help="where to look for projects (default: your home folder)")
    ap.add_argument("-l", "--list", action="store_true", help="print tables instead of the interactive UI")
    ap.add_argument("--json", action="store_true", help="print results as JSON")
    ap.add_argument("-m", "--min-size", default="0", metavar="SIZE",
                    help="hide items smaller than SIZE, e.g. 50M or 1G")
    group = ap.add_mutually_exclusive_group()
    group.add_argument("-P", "--projects-only", action="store_true", help="skip global caches")
    group.add_argument("-C", "--caches-only", action="store_true", help="skip the project scan")
    ap.add_argument("-w", "--workers", type=int, default=8, help="parallel size calculations (default 8)")
    ap.add_argument("--ascii", action="store_true", help="plain ASCII symbols (auto on old ncurses)")
    ap.add_argument("--unicode", action="store_true", help="force Unicode symbols")
    ap.add_argument("-V", "--version", action="version", version=f"{APP} {__version__}")
    args = ap.parse_args()

    root = os.path.abspath(os.path.expanduser(args.path))
    if not os.path.isdir(root):
        ap.error(f"not a directory: {root}")
    try:
        min_size = parse_size(args.min_size)
    except ValueError:
        ap.error(f"can't understand size: {args.min_size}")

    locale.setlocale(locale.LC_ALL, "")
    plain = args.list or args.json or curses is None or not sys.stdout.isatty()
    if plain:
        use_ascii = args.ascii or not utf8_locale()
    else:
        use_ascii = args.ascii or (not args.unicode and not unicode_safe())
    if use_ascii:
        G.update(ASCII_GLYPHS)

    scanner = Scanner(root, max(1, args.workers),
                      projects=not args.caches_only, caches=not args.projects_only).start()

    if plain:
        sys.exit(run_plain(scanner, min_size, args.json))

    os.environ.setdefault("ESCDELAY", "25")  # snappy Esc key
    holder = {}

    def ui(scr):
        app = App(scr, scanner, min_size)
        holder["app"] = app
        app.run()

    try:
        curses.wrapper(ui)
    except KeyboardInterrupt:
        pass

    final = holder["app"].sc if "app" in holder else scanner
    final.stop()
    if final.freed:
        print(f"Freed {human(final.freed)} across {final.cleaned} item(s). "
              f"Reinstall dependencies in a project whenever you need them again.")


def main():
    try:
        _main()
    except BrokenPipeError:  # e.g. piped into `head`
        try:
            sys.stdout = open(os.devnull, "w")
        except OSError:
            pass
        sys.exit(1)


if __name__ == "__main__":
    main()
